name: CML X-ray Classifier
description: AMP to build an image classifier for chest xrays using tensorflow
author: Jeff Fletcher
specification_version: 1.0
prototype_version: 1.0
date: "2021-05-19"
api_version: 1

tasks:
  - type: run_session
    name: Run project bootstrap
    script: code/_bootstrap.py
    kernel: python3
    memory: 4
    cpu: 2
    gpu: 0
